# Generated by Django 4.1.1 on 2022-09-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_wishlist_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='imageurl',
            field=models.CharField(default='not specified', max_length=140),
        ),
    ]
