# Generated by Django 4.1.1 on 2022-09-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_wishlist_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='title',
            field=models.CharField(default='not specified', max_length=140),
        ),
    ]
